version: '3'

services:
  dev:
    build:
      context: .
      # customize this dockerfile as needed
      dockerfile: dockerfiles/dev/Dockerfile
    devices:
      - /dev/snd
      - /dev/dri
    volumes:
      - .:/code
      # gtk requires some mounts for access to the desktop env
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/shm:/dev/shm
      # a data volume backs this directory so you can install whatever
      # tools you need and have them be there from run to run.
      - cargo-cache:/rust/cargo
    # You could launch watchexec to run your program, or tests...
    # As a default, the container will just exit
    command: /bin/true
    environment:
        - TERM
        - DISPLAY
        - RUST_BACKTRACE

volumes:
  cargo-cache:
